# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PTitle', models.CharField(max_length=100)),
                ('PContent', models.TextField()),
                ('PTime', models.DateTimeField()),
                ('PLastComTime', models.DateTimeField()),
                ('PTagLocation', models.CharField(max_length=50)),
                ('PTagClass', models.CharField(max_length=50)),
                ('PTagPrice', models.CharField(max_length=50)),
                ('PKeywords', models.CharField(max_length=100)),
                ('PDelete', models.BooleanField()),
                ('PLikeNum', models.IntegerField()),
                ('PSection', models.IntegerField()),
                ('PEssential', models.BooleanField()),
                ('PCheck', models.IntegerField()),
                ('PLimit', models.IntegerField()),
                ('PParentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantongbbs.Post')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UAccount', models.EmailField(max_length=254)),
                ('UName', models.CharField(max_length=50)),
                ('UPassword', models.CharField(max_length=50)),
                ('UImage', models.ImageField(upload_to='')),
                ('UAdmin', models.BooleanField()),
                ('UFollowUserNum', models.IntegerField()),
                ('UFollowPostNum', models.IntegerField()),
                ('UPostNum', models.IntegerField()),
                ('UForbidden', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantongbbs.Post')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantongbbs.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserLikePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantongbbs.Post')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantongbbs.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserReportPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReportContent', models.TextField()),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantongbbs.Post')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantongbbs.User')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='PUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantongbbs.User'),
        ),
        migrations.AddField(
            model_name='followuser',
            name='User1ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='fantongbbs.User'),
        ),
        migrations.AddField(
            model_name='followuser',
            name='User2ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='fantongbbs.User'),
        ),
    ]
