# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantongbbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PTagClass',
            field=models.CharField(choices=[('火锅', '火锅'), ('自助餐', '自助餐'), ('咖啡厅', '咖啡厅'), ('烧烤', '烧烤'), ('面包', '面包'), ('甜点', '甜点'), ('韩国料理', '韩国料理'), ('日本菜', '日本菜'), ('西餐', '西餐'), ('小吃快餐', '小吃快餐'), ('北京菜', '北京菜'), ('江浙菜', '江浙菜'), ('粤菜', '粤菜'), ('清真菜', '清真菜'), ('素菜', '素菜'), ('川菜', '川菜'), ('新疆菜', '新疆菜'), ('西北菜', '西北菜'), ('海鲜', '海鲜'), ('东南亚菜', '东南亚菜'), ('家常菜', '家常菜'), ('云南菜', '云南菜'), ('贵州菜', '贵州菜'), ('鲁菜', '鲁菜'), ('湖北菜', '湖北菜'), ('东北菜', '东北菜'), ('湘菜', '湘菜'), ('其他', '其他')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='PTagLocation',
            field=models.CharField(choices=[('海淀区', '海淀区'), ('朝阳区', '朝阳区'), ('东城区', '东城区'), ('西城区', '西城区'), ('丰台区', '丰台区'), ('石景山区', '石景山区'), ('大兴区', '大兴区'), ('通州区', '通州区'), ('昌平区', '昌平区'), ('房山区', '房山区'), ('顺义区', '顺义区'), ('门头沟区', '门头沟区'), ('怀柔区', '怀柔区'), ('平谷区', '平谷区'), ('延庆县', '延庆县'), ('密云县', '密云县')], max_length=50),
        ),
    ]
