# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantongbbs', '0007_auto_20160722_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbspost',
            name='PCheck',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PLikeNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PLimit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PSection',
            field=models.IntegerField(null=True),
        ),
    ]
