# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantongbbs', '0008_auto_20160722_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbspost',
            name='PDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PEssential',
            field=models.BooleanField(default=False),
        ),
    ]
