# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantongbbs', '0009_auto_20160722_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbsuser',
            name='UAccount',
        ),
        migrations.RemoveField(
            model_name='bbsuser',
            name='UName',
        ),
        migrations.RemoveField(
            model_name='bbsuser',
            name='UPassword',
        ),
        migrations.AddField(
            model_name='bbsuser',
            name='UForbiddenToTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bbsuser',
            name='UAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bbsuser',
            name='UFollowPostNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bbsuser',
            name='UFollowUserNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bbsuser',
            name='UForbidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bbsuser',
            name='UImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bbsuser',
            name='UPostNum',
            field=models.IntegerField(null=True),
        ),
    ]
