# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fantongbbs', '0010_auto_20160722_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbspost',
            name='PCheck',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PKeywords',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PLastComTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PLikeNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PLimit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PSection',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PTagClass',
            field=models.CharField(blank=True, choices=[('火锅', '火锅'), ('自助餐', '自助餐'), ('咖啡厅', '咖啡厅'), ('烧烤', '烧烤'), ('面包', '面包'), ('甜点', '甜点'), ('韩国料理', '韩国料理'), ('日本菜', '日本菜'), ('西餐', '西餐'), ('小吃快餐', '小吃快餐'), ('北京菜', '北京菜'), ('江浙菜', '江浙菜'), ('粤菜', '粤菜'), ('清真菜', '清真菜'), ('素菜', '素菜'), ('川菜', '川菜'), ('新疆菜', '新疆菜'), ('西北菜', '西北菜'), ('海鲜', '海鲜'), ('东南亚菜', '东南亚菜'), ('家常菜', '家常菜'), ('云南菜', '云南菜'), ('贵州菜', '贵州菜'), ('鲁菜', '鲁菜'), ('湖北菜', '湖北菜'), ('东北菜', '东北菜'), ('湘菜', '湘菜'), ('其他', '其他')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PTagLocation',
            field=models.CharField(blank=True, choices=[('海淀区', '海淀区'), ('朝阳区', '朝阳区'), ('东城区', '东城区'), ('西城区', '西城区'), ('丰台区', '丰台区'), ('石景山区', '石景山区'), ('大兴区', '大兴区'), ('通州区', '通州区'), ('昌平区', '昌平区'), ('房山区', '房山区'), ('顺义区', '顺义区'), ('门头沟区', '门头沟区'), ('怀柔区', '怀柔区'), ('平谷区', '平谷区'), ('延庆县', '延庆县'), ('密云县', '密云县')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PTagPrice',
            field=models.CharField(blank=True, choices=[('50以下', '50以下'), ('50-100', '50-100'), ('100-300', '100-300'), ('300以上', '300以上')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PTitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bbsuser',
            name='UFollowPostNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bbsuser',
            name='UFollowUserNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bbsuser',
            name='UPostNum',
            field=models.IntegerField(default=0),
        ),
    ]
