# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantongbbs', '0011_auto_20160723_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbsuser',
            name='UImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
