# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantongbbs', '0012_auto_20160723_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbspost',
            name='PFile',
            field=models.TextField(blank=True),
        ),
    ]
