# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantongbbs', '0013_bbspost_pfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbspost',
            name='PFile',
        ),
    ]
