# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantongbbs', '0014_remove_bbspost_pfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbspost',
            name='PTagClass',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PTagLocation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PTagPrice',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
