# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantongbbs', '0016_auto_20160726_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taginformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TClass', models.CharField(blank=True, choices=[('价位', '价位'), ('菜系', '菜系'), ('位置', '位置')], max_length=50)),
                ('TInfo', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PTagClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cla', to='fantongbbs.Taginformation'),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PTagLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc', to='fantongbbs.Taginformation'),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PTagPrice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pri', to='fantongbbs.Taginformation'),
        ),
    ]
