# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantongbbs', '0017_auto_20160727_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbspost',
            name='PTagClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cla', to='fantongbbs.Taginformation'),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PTagLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loc', to='fantongbbs.Taginformation'),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='PTagPrice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pri', to='fantongbbs.Taginformation'),
        ),
    ]
